Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4000"
  end
  config.vm.define "machine" do |manager|
    manager.vm.network :private_network, ip: "192.168.56.2"
  end
end
